### ISSUE TITLE
this error apper when i click on the database to open it

### ISSUE THREAD

**Issue by momaresh** [frappe/books#897] opened 2024-05-25 17:14 UTC
<h2>Description</h2>
Add some description...

<h2>Steps to Reproduce</h2>
Add steps to reproduce the error...

<h2>Info</h2>

**Error**: _TypeError: Cannot read properties of undefined (reading 'models')_

**Stack**:
```
TypeError: Cannot read properties of undefined (reading 'models')
    at SetupWizard._setDefaults (http://127.0.0.1:3000/@fs/C:/xampp/htdocs/books-master/fyo/model/doc.ts:268:40)
    at new _Doc (http://127.0.0.1:3000/@fs/C:/xampp/htdocs/books-master/fyo/model/doc.ts:41:10)
    at new SetupWizard (http://127.0.0.1:3000/@fs/C:/xampp/htdocs/books-master/models/baseModels/SetupWizard/SetupWizard.ts:54:5)
    at DocHandler.getNewDoc (http://127.0.0.1:3000/@fs/C:/xampp/htdocs/books-master/fyo/core/docHandler.ts:69:17)
    at getSetupWizardDoc (http://127.0.0.1:3000/utils/misc.ts:48:18)
    at Proxy.mounted (http://127.0.0.1:3000/pages/SetupWizard/SetupWizard.vue:65:22)
    at http://127.0.0.1:3000/@fs/C:/xampp/htdocs/books-master/node_modules/.vite/deps/chunk-HGK7C4TO.js?v=df143dd5:4260:88
    at callWithErrorHandling (http://127.0.0.1:3000/@fs/C:/xampp/htdocs/books-master/node_modules/.vite/deps/chunk-HGK7C4TO.js?v=df143dd5:1591:19)
    at callWithAsyncErrorHandling (http://127.0.0.1:3000/@fs/C:/xampp/htdocs/books-master/node_modules/.vite/deps/chunk-HGK7C4TO.js?v=df143dd5:1598:17)
    at hook.__weh.hook.__weh (http://127.0.0.1:3000/@fs/C:/xampp/htdocs/books-master/node_modules/.vite/deps/chunk-HGK7C4TO.js?v=df143dd5:4240:19)
```

**Version**: `0.21.2`
**Platform**: `win32`
**Path**: `/`
**Language**: `English`

**Comment by ableksaju** [comment] 2024-08-19 05:42
Are you currently still experiencing this issue? If so, could you please provide the steps to reproduce the problem?

**Comment by akshayitzme** [comment] 2024-08-30 06:56
@momaresh Closing this issue due to lack of replies. Please reopen with more context if the issue still persists

**Closed as completed by akshayitzme** 2024-08-30 06:56 UTC
