### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by alepouna** [frappe/books#668] opened 2023-06-21 06:06 UTC
Are there any plans for a Dark theme? Does it already exist? My eyes would appreciate :)

**Comment by 18alantom** [comment] 2023-06-26 10:41
Yup, will add it in a future update. The base UI may be overhauled to use the same design system as [`frappe-ui`](https://github.com/frappe/frappe-ui)

Closing this issue as of now cause duplicate of #224

**Closed as completed by 18alantom** 2023-06-26 10:41 UTC
Labels: enhancement
