### ISSUE TITLE
Status bar is cut off when editing templates

### ISSUE THREAD

**Issue by pyahmed** [frappe/books#758] opened 2023-10-17 13:55 UTC
I've started playing around with frappebooks and only by chance discovered that there is a more at the bottom off the screen. On my system it is almost entirely cut off. I've tried versions:
- 0.19
- 0.18
- 0.17.1
- 0.17
- 0.16

Always the same result. I didn't find anything related so I'm reporting it here :-)

System:
i5-9500T / Intel UHD 630
32 GB RAM
Windows 10  Pro - 19045.3570

![status_bar_frappebooks](https://github.com/frappe/books/assets/8441136/7b1958b2-7755-44ef-9986-3aed175497d5)

**Comment by ableksaju** [comment] 2024-08-13 12:42
@pyahmed  Are you still encountering this issue in the latest Frappe Books version?

**Comment by pyahmed** [comment] 2024-08-26 13:05
Just tried with 0.22 and it is still the same. I think same/similar problem here: #872

**Comment by akshayitzme** [comment] 2024-08-30 07:25
Closing this cause it's a duplicate of #872

**Closed as completed** 2024-08-30 07:25 UTC
Labels: ui
