### ISSUE TITLE
Getting this error on startup 

### ISSUE THREAD

**Issue by njmulsqb** [frappe/books#796] opened 2024-01-09 15:28 UTC
<h2>Description</h2>
Add some description...

<h2>Steps to Reproduce</h2>
Add steps to reproduce the error...

<h2>Info</h2>

**Error**: _Error: Cannot find latest.yml in the latest release artifacts (https://github.com/frappe/books/releases/download/v0.20.0/latest.yml): HttpError: 404 Not Found
"method: GET url: https://github.com/frappe/books/releases/download/v0.20.0/latest.yml\n\nPlease double check that your authentication token is correct. Due to security reasons, actual status maybe not reported, but 404.\n"
Headers: {
  "server": "GitHub.com",
  "date": "Tue, 09 Jan 2024 15:27:37 GMT",
  "content-type": "text/plain

**Comment by mildred** [comment] 2024-01-09 22:04
Thank you for your report.

This is caused by an error we are having to generate the next release we are going to publish soon. This is related to the automatic updates and you can ignore this error.

**Comment by mildred** [comment] 2024-01-15 10:09
It's not clear how to exclude draft releases from the update checks : https://www.electron.build/auto-update

**Comment by Isaac-GC** [comment] 2024-01-16 00:03
@mildred I think if we could use the alpha/beta channels for draft releases (https://www.electron.build/tutorials/release-using-channels.html), it might a quicker/easier way to solve the issue. 

I'm not too sure on this, but I've been thinking about adding in an option to choose the different release tracks if users wanted to do that. However, let me know your thoughts on this!

**Comment by mildred** [comment] 2024-01-16 21:52
I'm not sure this is possible, because during the time a release is built, it starts as a draft release without assets, and then assets are created.

alpha and beta channels require adding `-alpha` or `-beta` in the release name, but say we are releasing the next release `v0.21.0` it would mean creating first the `v0.21.0-beta`, and then rename the tag, but Git tags are not really meant to be renamed. And the version name needs to be renamed in package.json.

**Comment by Isaac-GC** [comment] 2024-01-19 17:22
Thats a fair point. That might add unnecessary complexity 😅  --> I looked a little deeper into the frappe books implementation of electron-builder and think have a simpl(-ish) solution... maybe

Currently, when publishing releases with electron-builder, the configuration is set to `always`. If we can change this to `onTag` and then only when drafting a release, we can add/configure the new tag into the github draft release (which I think we are doing?) --> it would solve the issue I think ([This is what I was looking at](https://www.electron.build/configuration/publish#how-to-publish)). --> Not sure on this though. Gonna build a separate POC to test it all out

**Comment by Isaac-GC** [comment] 2024-01-19 23:21
Sadly, I don't think we have an easy answer at this time. The electron-builder/electron-builder tool uses the Github API for the Atom feed and when drafting releases, it immediately up in the feed. There is not really anything you can check on *other* than if the <content> XML tag is empty, which isn't enough to use or properly check. 


Marking this is as a "known issue" and closing it

**Closed as completed by Isaac-GC** 2024-01-19 23:21 UTC
Labels: bug, known-issue
