### ISSUE TITLE
Make Payment not Working

### ISSUE THREAD

**Issue by imran300** [frappe/books#207] opened 2021-08-02 07:53 UTC
Hello, 
After invoice is completed, Make Payment window stuck while saving, See attachment.
![Capture](https://user-images.githubusercontent.com/7050400/127824312-f3ea592d-d324-4c6b-925d-9d673c63e508.PNG)

**Comment by 18alantom** [comment] 2021-10-20 10:42
Duplicate of #137

**Closed as completed by 18alantom** 2021-10-20 10:42 UTC
