### ISSUE TITLE
**Error**: _DatabaseError: Error

### ISSUE THREAD

**Issue by doanbactam** [frappe/books#877] opened 2024-04-02 07:59 UTC
<h2>Description</h2>
Add some description...

<h2>Steps to Reproduce</h2>
Add steps to reproduce the error...

<h2>Info</h2>

**Error**: _DatabaseError: Error
The specified module could not be found.
\\?\C:\Users\kisde\AppData\Local\Temp\2cFAyuhBnIxlXuLvNCvW1uaWw37\resources\app.asar.unpacked\node_modules\better-sqlite3\build\Release\better_sqlite3.node_

**Stack**:
```
Error: The specified module could not be found.
\\?\C:\Users\kisde\AppData\Local\Temp\2cFAyuhBnIxlXuLvNCvW1uaWw37\resources\app.asar.unpacked\node_modules\better-sqlite3\build\Release\better_sqlite3.node
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1869)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2096)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13377)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (C:\Users\kisde\AppData\Local\Temp\2cFAyuhBnIxlXuLvNCvW1uaWw37\resources\app.asar\node_modules\bindings\bindings.js:112:48)
    at new Database (C:\Users\kisde\AppData\Local\Temp\2cFAyuhBnIxlXuLvNCvW1uaWw37\resources\app.asar\node_modules\better-sqlite3\lib\database.js:48:64)
```

**Version**: `0.21.2`
**Platform**: `win32`
**Path**: `/index.html`
**Language**: `English`

**Comment by ableksaju** [comment] 2024-08-19 05:49
Are you currently still experiencing this issue? If so, could you please provide the steps to reproduce the problem?

**Comment by akshayitzme** [comment] 2024-08-30 06:56
@doanbactam Closing this issue due to lack of replies. Please reopen with more context if the issue still persists

**Closed as completed by akshayitzme** 2024-08-30 06:56 UTC
