### ISSUE TITLE
Print Templates bug

### ISSUE THREAD

**Issue by abrefael** [frappe/books#752] opened 2023-10-09 05:59 UTC
<h2>Template Type, Display Entry, Display Scale and Key Hints not showing by default</h2>
the buttons above aren't shown when entering the print template editor

<h2>Steps to Reproduce</h2>
Create a new template or duplicate an existing one.

<h2>Info</h2>

**Version**: `0.18.0`
**Platform**: `win32`
**Path**: `/template-builder/Minimal - Purchase Invoice CPY`
**Language**: `-`

<h2>Workaround</h2>
Hitting "Tab" key on keyboard until "Template Type" is selected and the top bar gets too short to accommodate its headers:

![image](https://github.com/frappe/books/assets/18067488/b414144d-b77b-422f-8fa1-f5c3b7967fc2)

**Comment by ableksaju** [comment] 2024-08-12 06:49
@abrefael Are you still encountering this issue in the latest Frappe Books version?

**Comment by abrefael** [comment] 2024-08-13 10:46
We stopped working with frappe books, I built a minimal system for my wife, based on a local frappe framework server.

**Comment by akshayitzme** [comment] 2024-08-19 06:28
Closing as couldn't reproduce. Please reopen if the issue still exists

**Closed as completed by akshayitzme** 2024-08-19 06:28 UTC
Labels: bug, ui
