### ISSUE TITLE
Supplier list is shown while creating invoice, mac beta 13

### ISSUE THREAD

**Issue by clipsess** [frappe/books#145] opened 2020-05-25 03:55 UTC
1. creating both customers and suppliers
2. create invoice, in the item selection, it shows the suppliers' list, not the customers' list

**Comment by ankitsinghaniyaz** [comment] 2021-08-19 16:57
I'm not able to reproduce this. More information will be helpful on this. Closing it for now.

**Closed as completed by ankitsinghaniyaz** 2021-08-19 16:57 UTC
