### ISSUE TITLE
Payments are going in drafts

### ISSUE THREAD

**Issue by Vanshbordia** [frappe/books#172] opened 2020-09-21 17:30 UTC
There is an issue where payments are recorded and done but saved as drafts and the dashboard also shows them unpaid. whereas the general ledger makes the duplicate of invoice making the records wrong.
![image](https://user-images.githubusercontent.com/22632594/93800406-2371b000-fc5e-11ea-9cd4-1cc57f4a270c.png)
![image](https://user-images.githubusercontent.com/22632594/93800429-2cfb1800-fc5e-11ea-8c51-6279a9ac55b3.png)
![image](https://user-images.githubusercontent.com/22632594/93800464-3a180700-fc5e-11ea-8b28-ec9fdf3ab56a.png)
![image](https://user-images.githubusercontent.com/22632594/93800485-456b3280-fc5e-11ea-89cb-5dac054eea73.png)

**Comment by saileshkush95** [comment] 2021-08-03 18:15
Did you find any way to resolve this issue

**Comment by ankitsinghaniyaz** [comment] 2021-08-19 16:28
I'm not able to reproduce this exact same thing but I've a similar issue. I created a purchase invoice submitted it and then deleted it. It still shows up an expense on my dashboard.

**Comment by 18alantom** [comment] 2021-11-03 05:37
Closing to prevent a pile-up, if recurring in 0.4 beta then will create a new issue.

**Closed as completed by 18alantom** 2021-11-03 05:37 UTC
Labels: bug
