### ISSUE TITLE
🐛 [Bug] - Collapsed sidebar can't be restored through a visible means

### ISSUE THREAD

**Issue by dbratell** [frappe/books#849] opened 2024-02-08 18:28 UTC
### Expected Behavior

The sidebar has a << symbol at the bottom, and clicking it collapses the sidebar into nothing. There should be some kind of >> symbol to get it back. Or a menu item. Or something. 

### Current Behavior

Clicking the << symbol at the sidebar bottom will collapse the sidebar but there is no visible way to get it back without restarting the program. There should be some kind of >> symbol to get it back. Or a menu item. Or something. The only things remaining visible are the arrows at the top and a looking glass symbol.

### Steps to Reproduce

1. Open demo project.
2. Click << icon in the sidebar.
3. See the sidebar disappear.
4. Look for a way to get it back and then write a github issue

### FrappeBooks Version

0.21.1

### Path or Feature name

Start page

### Country

IN

### Language

EN

### OS

Windows 10

**Comment by dbratell** [comment] 2024-02-08 18:31
I have found Shift+H in the documentation, which was funnily enough in the hidden sidebar. IMHO there still needs to be a visible way to restore the sidebar

**Comment by smalldale** [comment] 2024-02-21 16:17
I felt the same for the first time when I collapsed the sidebar.
Hover it to the position where the collapse button is. It's only shown when hovering.
![image](https://github.com/frappe/books/assets/49019693/aa628e1e-2bb2-4c26-9190-b3ab6ebce13a)

**Comment by ableksaju** [comment] 2024-08-12 05:08
@dbratell  Do you still need help with this issue ?

**Comment by dbratell** [comment] 2024-08-12 06:46
I did not file a support request. It is a report about a flawed UI. Personally I've moved on and am not concerned either way.

**Comment by akshayitzme** [comment] 2024-08-13 06:00
Closing it as couldn't reproduce the same.

**Closed as completed by akshayitzme** 2024-08-13 06:00 UTC
Labels: bug
