### ISSUE TITLE
Error in Stock Balance report

### ISSUE THREAD

**Issue by MAMvaladi** [frappe/books#871] opened 2024-03-26 06:53 UTC
<h2>Description</h2>
Add some description...

<h2>Steps to Reproduce</h2>
Add steps to reproduce the error...

<h2>Info</h2>

**Error**: _Error: invalid input '-Infinity' of type 'string' value: '-Infinity', type: number_

**Stack**:
```
Error: invalid input '-Infinity' of type 'string' value: '-Infinity', type: number
    at XX (app://assets/index-c659ca9f.js:11:34056)
    at ZX (app://assets/index-c659ca9f.js:11:33635)
    at kf._f (app://assets/index-c659ca9f.js:11:38357)
    at set value [as value] (app://assets/index-c659ca9f.js:11:36453)
    at new kf (app://assets/index-c659ca9f.js:11:35380)
    at new Dv (app://assets/index-c659ca9f.js:11:39496)
    at qX (app://assets/index-c659ca9f.js:11:44205)
    at vK.pesa (app://assets/index-c659ca9f.js:11:44263)
    at gK (app://assets/index-c659ca9f.js:40:5806)
    at mK (app://assets/index-c659ca9f.js:40:5610)
```

**Version**: `0.21.2`
**Platform**: `win32`
**Path**: `/report/StockBalance`
**Language**: `English`
**Country**: `in`

**Comment by akshayitzme** [comment] 2024-08-14 06:41
closing as duplicate of #842

**Closed as completed by akshayitzme** 2024-08-14 06:41 UTC
