### ISSUE TITLE
Error when just opened the folder

### ISSUE THREAD

**Issue by umairsy** [frappe/books#524] opened 2023-01-12 08:54 UTC
<h2>Description</h2>
Add some description...

<h2>Error Info</h2>

**Error**: _DatabaseError: Error
Unable to acquire a connection_

**Stack**:
```
Error: Unable to acquire a connection
    at Client_BetterSQLite3.acquireConnection (/private/var/folders/2w/sfv9wx3s7jd10n6t0_1yr8f00000gn/T/AppTranslocation/646EF21F-E24A-47E5-B5BC-A1C0A6CF6794/d/Frappe Books 2.app/Contents/Resources/app.asar/node_modules/knex/lib/client.js:298:13)
    at Runner.ensureConnection (/private/var/folders/2w/sfv9wx3s7jd10n6t0_1yr8f00000gn/T/AppTranslocation/646EF21F-E24A-47E5-B5BC-A1C0A6CF6794/d/Frappe Books 2.app/Contents/Resources/app.asar/node_modules/knex/lib/execution/runner.js:294:46)
    at Runner.run (/private/var/folders/2w/sfv9wx3s7jd10n6t0_1yr8f00000gn/T/AppTranslocation/646EF21F-E24A-47E5-B5BC-A1C0A6CF6794/d/Frappe Books 2.app/Contents/Resources/app.asar/node_modules/knex/lib/execution/runner.js:30:30)
    at QueryBuilder_SQLite3.Target.then (/private/var/folders/2w/sfv9wx3s7jd10n6t0_1yr8f00000gn/T/AppTranslocation/646EF21F-E24A-47E5-B5BC-A1C0A6CF6794/d/Frappe Books 2.app/Contents/Resources/app.asar/node_modules/knex/lib/builder-interface-augmenter.js:24:43)
```

**Version**: `0.8.0`
**Platform**: `darwin`
**Path**: `/index.html`
**Language**: `undefined`

**Comment by 18alantom** [comment] 2023-03-06 05:50
Closing cause duplicate of #468

**Closed as completed by 18alantom** 2023-03-06 05:50 UTC
Labels: bug
